# Generated by Django 5.1.3 on 2024-12-23 11:39

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.collections
import django.contrib.gis.geos.polygon
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_orderitem_download_guid_alter_order_order_status_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='excludedGeom',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=2056, verbose_name='excludedGeom'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='download_guid',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='download_guid'),
        ),
        migrations.CreateModel(
            name='ProductOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(default=django.contrib.gis.geos.collections.MultiPolygon(django.contrib.gis.geos.polygon.Polygon(((2828694.200665463, 1075126.8548189853), (2828694.200665463, 1299777.3195268118), (2484749.5514877755, 1299777.3195268118), (2484749.5514877755, 1075126.8548189853), (2828694.200665463, 1075126.8548189853)))), srid=2056, verbose_name='geom')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.product', verbose_name='product')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='user_group')),
            ],
        ),
    ]
