# Generated by Django 5.2 on 2025-05-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_product_max_order_area_alter_order_part_vat_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('DE', 'German'), ('FR', 'French')], default='DE', null=True, max_length=10, verbose_name='language'),
        ),
    ]
