# Generated by Django 5.2.7 on 2025-10-15 13:47

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_order_extract_result_size_and_more'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='metadata',
            trigger=pgtrigger.compiler.Trigger(name='update_search_vector_on_change', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                    IF EXISTS\n                        ( SELECT 1\n                        FROM   information_schema.tables\n                        WHERE  table_schema = CURRENT_SCHEMA()\n                        AND    table_name = 'product'\n                        )\n                    THEN\n                        UPDATE product\n                        SET ts = to_tsvector('french', label || ' ' || NEW.description_long) ||\n                                to_tsvector('german', label || ' ' || NEW.description_long) ||\n                                to_tsvector('italian', label || ' ' || NEW.description_long)\n                        WHERE metadata_id = NEW.id;\n                    END IF ;\n                    RETURN NEW;\n                ", hash='631baaa3d173a38c3ce9bd176f7a233ce1246983', operation='UPDATE', pgid='pgtrigger_update_search_vector_on_change_86c20', table='metadata', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='product',
            trigger=pgtrigger.compiler.Trigger(name='update_search_vector_on_change', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE description TEXT;', func="\n                    SELECT description_long INTO description FROM metadata WHERE id = NEW.metadata_id;\n                    NEW.ts := to_tsvector('french', NEW.label || ' ' || description) ||\n                            to_tsvector('german', NEW.label || ' ' || description) ||\n                            to_tsvector('italian', NEW.label || ' ' || description);\n                    RETURN NEW;\n                ", hash='da6d53ac164d4432ac3dcd6a8f93323e2b941b07', operation='UPDATE OR INSERT', pgid='pgtrigger_update_search_vector_on_change_86bf9', table='product', when='BEFORE')),
        ),
    ]
