# Generated by Django 5.2.8 on 2026-03-03 10:32
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_metadata_update_search_vector_on_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='extract_result_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='extract_result_size'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='extract_result_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='extract_result_size'),
        ),
    ]
