# Generated by Django 5.2.8 on 2026-03-03 10:32

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.collections
import django.contrib.gis.geos.polygon
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_metadata_update_search_vector_on_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('DE', 'German'), ('FR', 'French')], default='FR', max_length=10, null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='order',
            name='extract_result_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='extract_result_size'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='extract_result_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='extract_result_size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(default=django.contrib.gis.geos.collections.MultiPolygon(django.contrib.gis.geos.polygon.Polygon(((2420000, 1030000), (2420000, 1360000), (2900000, 1360000), (2900000, 1030000), (2420000, 1030000)))), srid=2056, verbose_name='geom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_order_area',
            field=models.IntegerField(default=0.0, verbose_name='max_order_area'),
        ),
        migrations.AlterField(
            model_name='productownership',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(default=django.contrib.gis.geos.collections.MultiPolygon(django.contrib.gis.geos.polygon.Polygon(((2420000, 1030000), (2420000, 1360000), (2900000, 1360000), (2900000, 1030000), (2420000, 1030000)))), srid=2056, verbose_name='geom'),
        ),
    ]
