
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE SCHEMA IF NOT EXISTS geoshop AUTHORIZATION geoshop;

DROP TEXT SEARCH CONFIGURATION IF EXISTS fr;
CREATE TEXT SEARCH CONFIGURATION fr (COPY = simple);
DROP TEXT SEARCH CONFIGURATION IF EXISTS en;
CREATE TEXT SEARCH CONFIGURATION en (COPY = simple);
DROP TEXT SEARCH CONFIGURATION IF EXISTS de;
CREATE TEXT SEARCH CONFIGURATION de (COPY = simple);

ALTER TEXT SEARCH CONFIGURATION fr ALTER MAPPING FOR hword, hword_part, word
WITH unaccent, simple;
ALTER TEXT SEARCH CONFIGURATION de ALTER MAPPING FOR hword, hword_part, word
WITH unaccent, simple;
